name: Build and push release
run-name: Building binaries and updating release artifacts
on:
  push:
    branches:
      - master
jobs:
  Build_for_DEB:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: "sudo apt update"
      - run: "sudo apt install -y gcc g++ autotools-dev fuse3 libfuse-dev libfuse3-dev libattr1-dev alien"
      - run: "mkdir -p packaging/debian/usr/bin"
      - run: "make cicpoffs"
      - run: "cp cicpoffs packaging/debian/usr/bin/cicpoffs"
      - run: "chmod 0755 packaging/debian/usr/bin/cicpoffs"
      - run: "ln -s cicpoffs packaging/debian/usr/bin/mount.cicpoffs"
      - run: "dpkg-deb --build packaging/debian"
      - run: "cp packaging/debian.deb packaging/cicpoffs.deb"
      - uses: actions/upload-artifact@v7
        with:
          name: cicpoffs.deb
          path: packaging/debian.deb
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: packaging/cicpoffs.deb
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
  Build_for_RPM:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fedora_version: [43, 44]
    steps:
      - uses: actions/checkout@v6
      - run: "docker run --rm -v ./:/repo fedora:${{ matrix.fedora_version }} /bin/bash /repo/packaging/fedora/build.sh ${{ matrix.fedora_version }}"
      - uses: actions/upload-artifact@v7
        with:
          name: cicpoffs-fc${{ matrix.fedora_version }}.rpm
          path: packaging/cicpoffs-fc${{ matrix.fedora_version }}.rpm
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: packaging/cicpoffs-fc${{ matrix.fedora_version }}.rpm
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
  Build_for_ARCH:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: "docker run --rm -v ./:/repo archlinux /bin/bash /repo/packaging/arch/bash.sh"
      - run: "sudo cp packaging/arch/cicpoffs.tar.zst packaging/cicpoffs.tar.zst"
      - uses: actions/upload-artifact@v7
        with:
          name: cicpoffs.tar.zst
          path: packaging/arch/cicpoffs.tar.zst
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: packaging/cicpoffs.tar.zst
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
